# Generated by Django 2.0.6 on 2018-06-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
    ]
